name = input("Enter Your Name : ")
branch = input("Enter Your Branch : ")
regno = input("Enter Your Registered Number : ")
age  = input("Enter Your Age : ")

print(f"Hello! Mrs/Ms {name}. Glad To See Youh As Of My Knowledge Your Registered Number Is {regno} And Your Branch is {branch} And Your Age Is {age}  This IS Generated By F Strings Method")